### ISSUE TITLE
The dependency fx/System.XML could not be resolved.

### ISSUE THREAD

**Issue by mleader1** [IdentityServer/IdentityServer4#14]
Hi ASP.NET 5 Newbbie here...

I'm loading up a new blank ASP.NET 5 project in Mac (using Xamarin with DNX addin for ASP.NET 5 support), I can build the ASP.NET 5 web application "Hello world" without problem, however once I add the Nuget package IdentityServer4 it then gave me an error  "The dependency fx/System.XML could not be resolved" compilation error.

Is that something related to IdentityServer4?  I see it is stated to work in Core 1.0 ?  Have I missed anything...

Many thanks.

Lida

**Comment by leastprivilege** [comment]
you probably try to push your luck a little bit too far.

try Windows and Visual Studio first - then go from there ;)

**Comment by mleader1** [comment]
tried to add dependency System.Xml but the error didn't go away so I ran out of luck this time. :dart: 
VS 2015 on VM is the way to go...
Cheers
